### ISSUE TITLE
Problem with optics_add

### ISSUE THREAD

**Issue by hannahrbridges** [afanasyevp/afis#1]
Hi, I have tried using your AFIS scripts and the split one works nicely analysing the clusters, however with the optics_add script I keep getting the following error:

Traceback (most recent call last):
  File "optics_add.py", line 246, in <module>
    main()
  File "optics_add.py", line 242, in main
    micrographs_write_optics(movies_filename, star_filename, str(args.o))
  File "optics_add.py", line 144, in micrographs_write_optics
    OpticsFile_MainHeader, OpticsGroupData, OpticsHeader, MoviesData, StarFileType = star_analyze(OpticsFileName)
  File "optics_add.py", line 95, in star_analyze
    StarData[star_line[(_rlnMicrographMovieName_index-1)]]=star_line
UnboundLocalError: local variable '_rlnMicrographMovieName_index' referenced before assignment

I have removed the optics group information from the input particle star file and the only place where this header '_rlnMicrographMovieName_index' occurs is in the output movies.star file from optics_split.py. 

Any idea what could be going wrong?

Cheers!
Hannah

**Comment by afanasyevp** [comment]
Hi Hannah,

Thanks for the feedback and I am sorry about this problem. Could you send me your star files (does not have to be the full) on pafanasyev[at]ethz.ch and I will try to fix the issue?

Cheers,
Pavel

**Comment by afanasyevp** [comment]
Fixed
